- name: Add fvosburgh user to docker group
  user:
    name: fvosburgh
    groups: docker
    append: yes

- name: Download RKE 0.1.18
  get_url:
    url: https://github.com/rancher/rke/releases/download/v0.1.18/rke_linux-amd64
    dest: /usr/bin/rke
    mode: 555
  become: true

- name: Copy cluster config
  copy:
    src: files/rke-config.yaml
    dest: /home/fvosburgh/cluster.yml
    owner: fvosburgh
    mode: 400

- name: Install k8s cluster with rke
  shell: rke up
  args:
    chdir: /home/fvosburgh
